services:
  # db:
  #   image: mariadb
  #   restart: always
  #   container_name: hackujstatdb
  #   ports:
  #     - "${DB_PORT}:3306"
  #   volumes:
  #     - ./mariadb_data:/var/lib/mysql
  #   env_file:
  #     - .env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "${ADMINER_PORT}:8080"

  backend:
    build:
      context: .
    restart: always
    container_name: hackujstatbackend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
