curl -I https://hackujapi.ladislavpokorny.cz/school/finance/2312
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/2212
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/2112
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/2012
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1912
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1812
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1712
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1612
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1512
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1412
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1312
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1212
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1112
curl -I https://hackujapi.ladislavpokorny.cz/school/finance/1012